### ISSUE TITLE
Move repository to the mist-devel organization

### ISSUE THREAD

**Issue by harbaum** [mist-devel/fpgagen#58]
This started as a personal fork to try a different CPU core (which btw has been replaced once more). Now that this is main fpgagen core for mist i'd like to move ownership of this repository to the mist-devel organization.

Any objections?

**Comment by gyurco** [comment]
It's OK for me if it will remain a top-level repo, with preserved history.

**Comment by harbaum** [comment]
I'd move using the github mechanisms for this. That will imho not change the history etc

**Comment by gyurco** [comment]
Let's hope the best.

**Comment by harbaum** [comment]
Done

**Comment by gyurco** [comment]
Seems worked. Now I'm thinking about transfering my cores, too (ZX80-81, Apple2e, VIC20, PCE, MSX).

**Comment by gyurco** [comment]
Also it would be good to protect these repos from force-pushes: in settings/branches/branch protection rules/add rules - branch name pattern: master
Maybe with "include administrators". I think only you can do this in mist-devel.
