### ISSUE TITLE
Support for keyboard during gameplay

### ISSUE THREAD

**Issue by retrofan1979** [mist-devel/fpgagen#74]
Hi, can you please add support for USB keyboard during gameplay? Now I have to use my gamepad, but I prefer to use my USB keyboard. Thank you!

**Comment by gyurco** [comment]
Press Num Lock -> use the joystick emulation via the cursor+modifier keys.

**Comment by retrofan1979** [comment]
Thanks, it works! And is there a way to re-assign the action keys for keyboard?
